### ISSUE TITLE
Redirect docs

### ISSUE THREAD

**Issue by amakko** [grantjenks/python-diskcache#150] opened 2020-06-16 10:52 UTC
Link
http://www.grantjenks.com/docs/diskcache/
redirect to
https://www.kjxqz.com/docs/diskcache/ 
and site not work
`404 Not Found
nginx/1.10.3 (Ubuntu)`

**Comment by grantjenks** [comment] 2020-06-16 13:27
Don’t use https. Your browser is doing the redirect.

I’ve seen this a couple different places. Is https some kind of corporate policy thing?

**Comment by grantjenks** [comment] 2020-08-23 22:51
Duplicate of #141

**Closed by grantjenks** 2020-08-23 22:51 UTC
