### ISSUE TITLE
1 test fails: AttributeError: can't set attribute

### ISSUE THREAD

**Issue by yurivict** [grantjenks/python-diskcache#262] opened 2022-08-14 17:25 UTC
```
======================================================================
ERROR: test_cache_write_unpicklable_object (tests.test_djangocache.DiskCacheTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/disk-samsung/freebsd-ports/devel/py-diskcache/work-py39/python-diskcache-5.4.0/tests/test_djangocache.py", line 873, in test_cache_write_unpicklable_object
    fetch_middleware.cache = cache
AttributeError: can't set attribute

----------------------------------------------------------------------
Ran 64 tests in 19.004s
```

Version: 5.4.0
Python-3.9
FreeBSD 13.1

**Comment by grantjenks** [comment] 2022-08-14 18:24
Dupe of #260

**Closed by grantjenks** 2022-08-14 18:24 UTC
