### ISSUE TITLE
Cache.db problem after upgrading to latest version 3.1.0

### ISSUE THREAD

**Issue by h3llrais3r** [grantjenks/python-diskcache#89] opened 2018-11-16 17:10 UTC
After upgrading to the latest version, I'm always getting the following error.
It seems that the cache file gets created, but without db structure...

I'm not sure if it's OS related, but I'm using Windows.

```
Traceback (most recent call last):
  File "C:\Tools\GitHub\Auto-Subliminal\autosubliminal\indexer.py", line 210, in get_imdb_id_and_year
    imdb_id, year = self._query_api(title, year)
  File "C:\Tools\GitHub\Auto-Subliminal\autosubliminal\indexer.py", line 148, in _query_api
    imdb_movies = api.search_for_title(title)
  File "C:\Tools\GitHub\Auto-Subliminal\lib\imdbpie\imdbpie.py", line 182, in search_for_title
    search_results = self._suggest_search(title)
  File "C:\Tools\GitHub\Auto-Subliminal\lib\imdbpie\imdbpie.py", line 160, in _suggest_search
    search_results = self._get(url=url, query=query_encoded)
  File "C:\Tools\GitHub\Auto-Subliminal\lib\imdbpie\imdbpie.py", line 307, in _get
    headers.update(self.get_auth_headers(full_url))
  File "C:\Tools\GitHub\Auto-Subliminal\lib\imdbpie\auth.py", line 112, in get_auth_headers
    creds, soon_expires = self._creds_soon_expiring()
  File "C:\Tools\GitHub\Auto-Subliminal\lib\imdbpie\auth.py", line 97, in _creds_soon_expiring
    creds = self._get_creds()
  File "C:\Tools\GitHub\Auto-Subliminal\lib\imdbpie\auth.py", line 84, in _get_creds
    with diskcache.Cache(directory=self._cachedir) as cache:
  File "C:\Tools\GitHub\Auto-Subliminal\lib\diskcache\core.py", line 413, in __init__
    self.reset(key, value, update=False)
  File "C:\Tools\GitHub\Auto-Subliminal\lib\diskcache\core.py", line 1927, in reset
    (old_value,), = sql('PRAGMA %s' % (pragma)).fetchall()
ValueError: need more than 0 values to unpack
```

It seems to be a problem for the `sqlite_mmap_size` key.

![image](https://user-images.githubusercontent.com/1945295/48637341-c061c300-e9cd-11e8-9162-fdee961fa87d.png)

Reverting back to the previous version 3.0.6 fixes the problem.

**Comment by grantjenks** [comment] 2018-11-16 19:39
Interesting. Thanks for the traceback and debug view. What's the result of:

```
sql('PRAGMA %s' % (pragma)).fetchall()
```

At the point of failure?

I've made branch issue-89 and pull request #90 with a small code change to observe the result.

Maybe the sqlite version embedded in your python interpreter lacks mmap support? I'm not sure how to reproduce the problem locally.

**Comment by h3llrais3r** [comment] 2018-11-16 20:04
Well, the thing you mentioned about the sqlite version was also my first thought.
Being that, I've just upgraded py python installation from version 2.7.9 to 2.7.15, which fixes the problem.
So this probably confirms that it's related to the sqlite version packaged with the python distribution.

**Comment by h3llrais3r** [comment] 2018-11-16 20:23
@grantjenks I've just tested your changes and this is the output:

![image](https://user-images.githubusercontent.com/1945295/48645397-de3b2200-e9e5-11e8-9a93-1eac37533dbd.png)

**Comment by grantjenks** [comment] 2018-11-22 16:11
I thought I had updated this thread so apologies if this is duplicate.

I've included a fix for this issue in #90. Could you test on your end? Here's how to do so:

```
$ git clone git@github.com:grantjenks/python-diskcache.git diskcache-test
$ cd diskcache-test/
$ git checkout issue-89
$ python2.7 -m virtualenv env27
$ source env27/bin/activate
$ pip install "Django<2" nose mock
$ nosetests
```

It takes about a minute to run all the tests on my machine and they all pass. If you could validate these changes with your older version of python 2.7 then I will merge and deploy a new version.

**Comment by grantjenks** [comment] 2018-11-22 18:35
Thanks! I will merge and deploy.

The errors I see are all pragma related (one way or another). The concurrency stress tests are failing due to assumptions about the journal mode ("wal" expected, but only "delete" supported in your old build).

**Comment by grantjenks** [comment] 2018-11-22 18:59
Deployed at version 3.1.1

**Closed by grantjenks** 2018-11-22 18:59 UTC
